### ISSUE TITLE
Hello, I want to add new links to the site

### ISSUE THREAD

**Issue by mehmet-biter** [openware/baseapp#403]
Hello, I want to add new links to the site. Can you help me with this?
![fff](https://user-images.githubusercontent.com/14812826/104138700-ecfba480-53b6-11eb-9f4b-b32225ade27f.PNG)

**Comment by josadcha** [comment]
Hello @mehmet-biter!
Thanks for using baseapp.

In order to change links on Landing page you need to edit `src/screens/LandingScreen/index.tsx` file
Links of footer lies here (see screenshot)
![image](https://user-images.githubusercontent.com/39953699/105840205-4da3f780-5fdb-11eb-8232-371438f332e3.png)

**Comment by mehmet-biter** [comment]
> Merhaba @ mehmet-biter !
> Baseapp kullandığınız için teşekkürler.
> 
> Açılış sayfasındaki bağlantıları değiştirmek için `src/screens/LandingScreen/index.tsx`dosyayı düzenlemeniz gerekir
> . Altbilgi bağlantıları burada bulunur (ekran görüntüsüne bakın)
> ![görüntü](https://user-images.githubusercontent.com/39953699/105840205-4da3f780-5fdb-11eb-8232-371438f332e3.png)

**Comment by mehmet-biter** [comment]
> Hello @mehmet-biter!
> Thanks for using baseapp.
> 
> In order to change links on Landing page you need to edit `src/screens/LandingScreen/index.tsx` file
> Links of footer lies here (see screenshot)
> ![image](https://user-images.githubusercontent.com/39953699/105840205-4da3f780-5fdb-11eb-8232-371438f332e3.png)

thank you for your answer i did it
